<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\SistemaGestaoChamados.Domain\SistemaGestaoChamados.Domain.csproj" />
		<ProjectReference Include="..\SistemaGestaoChamados.Infrastructure\SistemaGestaoChamados.Infrastructure.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>